Replaced Docker with Podman

diff --git a/infrastructure/Makefile b/infrastructure/Makefile
--- a/infrastructure/Makefile
+++ b/infrastructure/Makefile
@@ -1,4 +1,10 @@
-IMAGE_NAME := cesentry-firmware-builder
+IMAGE_NAME := asciidoxy-builder
+
+--check-%:
+	@if [ "`command -v ${*}`" = "" ]; then \
+		echo "Command ${*} not found in path";  \
+		exit 1; \
+	fi
 
 --guard-%:
 	@if [ "${${*}}" = "" ]; then \
@@ -6,14 +12,14 @@ IMAGE_NAME := cesentry-firmware-builder
 		exit 1; \
 	fi
 
-build:
+build: --check-podman
 	podman build -t $(IMAGE_NAME) -f Containerfile
 
-docker-push: --guard-VERSION build
+docker-push: --check-podman --guard-VERSION build
 	podman login docker.io
 	podman push $(IMAGE_NAME):latest docker.io/$(USER)/$(IMAGE_NAME):$(VERSION)
 
-gitlab-push: --guard-REGISTRY_URL --guard-VERSION build
+gitlab-push: --check-podman --guard-REGISTRY_URL --guard-VERSION build
 	podman login $(REGISTRY_URL)
 	podman push --tls-verify=false  \
 		$(IMAGE_NAME):latest $(REGISTRY_URL)/documentation/cesentry-firmware/$(IMAGE_NAME):$(VERSION)
